"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['zfsgui.py']
DATA_FILES = ['openzfs.icns']
OPTIONS = {
    'iconfile':'zfsgui.icns',
    'plist': {'LSUIElement': True},
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
